# Generated by Django 4.2 on 2023-06-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_Organizer', '0003_note_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='email',
            field=models.CharField(max_length=128),
        ),
    ]
