# Generated by Django 4.2 on 2023-06-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_Organizer', '0004_alter_note_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='note',
        ),
    ]
