# Generated by Django 4.2 on 2023-06-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_Organizer', '0006_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_users',
            name='theme_c1',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='web_users',
            name='theme_c2',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='web_users',
            name='theme_c3',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='web_users',
            name='theme_c4',
            field=models.CharField(default='', max_length=128),
        ),
    ]
